# Generated by Django 3.0.11 on 2020-11-06 15:59

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_populate_homepagegalleryitemnew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagegalleryitem',
            name='galleryitem_ptr',
        ),
        migrations.RemoveField(
            model_name='homepagegalleryitem',
            name='page',
        ),
        migrations.AlterField(
            model_name='homepagegalleryitemnew',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='home.HomePage'),
        ),
        migrations.DeleteModel(
            name='GalleryItem',
        ),
        migrations.DeleteModel(
            name='HomePageGalleryItem',
        ),
    ]
